name: SearchableInfiniteShop
version: 1.0.0
main: ryuzuinfiniteshop.ryuzuinfiniteshop.RyuZUInfiniteShop
api-version: 1.13
description: 無限にページを作成できるShopPluginです
softdepend:
  - MythicMobs

commands:
  sis:
    usage:  /sis
    description: SearchableInfiniteShopのコマンド

permissions:
  sis.player:
    default: true
  sis.op:
    default: op
  sis.*:
    children:
      sis.op: true
      sis.player: true